### ISSUE TITLE
Real-time list of VMs from ESXi 

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/k8-vmware#19]
First: Script to get all servers in real-time from ESXi and update into a MD file. 

Then, we need to know the version that each server has running with the tag from the release. Also @faisaladnanpeltops will take this information to display in a dashboard.

**Comment by naderaly** [comment]
Hello @GINAGC, I have couple of questions:
1) by get all servers you mean just list all the VMs name on a specific ESXi server  ?
2) what do you mean by the version that each server has running ?
Thank you

**Comment by GINAGC** [comment]
1.- Yes, lets start with the name of the VM. What other useful information can we get? tags, status (running, shutdown), OS installed?
2.- The plan would be later to know the release version they are running https://github.com/k8-proxy/GW-Releases/tags 

In general, we want to display all this information in dashboards and get a very quick view on what is going on in the ESXi servers, So anything that you consider useful for that goal, please add it.

**Comment by dinis-cruz-gw** [comment]
note this code is not going to go on this repo (only code changes in k8-vmare should be related to the APIs that exist here )

**Comment by naderaly** [comment]
Thank you @GINAGC , working on it.
Thank you @dinis-cruz-gw , noted

**Comment by GINAGC** [comment]
Issue moved to [k8-proxy/vmware-scripts #73](https://github.com/k8-proxy/vmware-scripts/issues/73) via [**ZenHub**](https://www.zenhub.com/)
