### ISSUE TITLE
add step to GitHub Actions to check if the runner has access to the ESXI credentials

### ISSUE THREAD

**Issue by dinis-cruz-gw** [k8-proxy/k8-vmware#7]
so that we don't get an error like this

![image](https://user-images.githubusercontent.com/57914593/103909315-767f4e00-50fb-11eb-9c25-1a29017226a1.png)

this API can be used 

```        
with Sdk_User(user_id=self.user_id, password=self.password) as sdk_user:                    
            assert sdk_user.login_result is True                                                              
```

**Comment by anejaalekh** [comment]
@dinis-cruz-gw @DinisCruz Do you want to stop the execution if ESXI credentials are missing or are incorrect?

Solution Proposal: A simple action can be added which executes a single test which validates the credentials and would proceed to further action if successful.
